2015-01-16 19:45:17 Error: Fatal Error (1): Class 'Locale' not found in [/home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/I18n/I18n.php, line 235]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-01-16 20:33:20 Error: [Cake\Controller\Exception\MissingActionException] Action CuentasController::hola() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'CuentasController',
  'action' => 'hola',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cakephp/cuentas/hola
Stack Trace:
#0 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#2 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-01-16 20:38:05 Error: Fatal Error (4): syntax error, unexpected 'print_f' (T_STRING) in [/home/cra12733/public_html/cakephp/src/Controller/CuentasController.php, line 32]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-01-16 20:38:05 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'print_f' (T_STRING)
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', '/home/cra12733/...', 32)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-01-16 20:38:23 Error: Fatal Error (4): syntax error, unexpected '}' in [/home/cra12733/public_html/cakephp/src/Controller/CuentasController.php, line 32]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-01-16 20:38:23 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}'
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', '/home/cra12733/...', 32)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-01-16 21:09:35 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cra12733_cakephp.cuentas' doesn't exist
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Database/Schema/Collection.php(96): Cake\Database\Schema\Collection->_reflect('Column', 'cuentas', Array, Object(Cake\Database\Schema\Table))
#1 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Database/Schema/CachedCollection.php(65): Cake\Database\Schema\Collection->describe('cuentas', Array)
#2 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php(364): Cake\Database\Schema\CachedCollection->describe('cuentas')
#3 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Query.php(147): Cake\ORM\Table->schema()
#4 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Query.php(129): Cake\ORM\Query->addDefaultTypes(Object(App\Model\Table\CuentasTable))
#5 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php(1073): Cake\ORM\Query->__construct(Object(Cake\Database\Connection), Object(App\Model\Table\CuentasTable))
#6 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php(822): Cake\ORM\Table->query()
#7 /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php(31): Cake\ORM\Table->find()
#8 [internal function]: App\Controller\CuentasController->index()
#9 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Controller/Controller.php(406): call_user_func_array(Array, Array)
#10 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#11 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#12 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-01-16 21:11:48 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "cuentas"
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php(1036): Cake\ORM\Query->firstOrFail()
#1 /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php(31): Cake\ORM\Table->get(100)
#2 [internal function]: App\Controller\CuentasController->index()
#3 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Controller/Controller.php(406): call_user_func_array(Array, Array)
#4 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#5 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#6 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 {main}


2015-01-16 21:11:50 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "cuentas"
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php(1036): Cake\ORM\Query->firstOrFail()
#1 /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php(31): Cake\ORM\Table->get(100)
#2 [internal function]: App\Controller\CuentasController->index()
#3 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Controller/Controller.php(406): call_user_func_array(Array, Array)
#4 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#5 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#6 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 {main}


2015-01-16 21:11:51 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "cuentas"
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php(1036): Cake\ORM\Query->firstOrFail()
#1 /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php(31): Cake\ORM\Table->get(100)
#2 [internal function]: App\Controller\CuentasController->index()
#3 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Controller/Controller.php(406): call_user_func_array(Array, Array)
#4 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#5 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#6 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 {main}


2015-01-16 21:11:53 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "cuentas"
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php(1036): Cake\ORM\Query->firstOrFail()
#1 /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php(31): Cake\ORM\Table->get(100)
#2 [internal function]: App\Controller\CuentasController->index()
#3 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Controller/Controller.php(406): call_user_func_array(Array, Array)
#4 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#5 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#6 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 {main}


2015-01-16 21:12:25 Warning: Warning (2): Missing argument 1 for Cake\ORM\Table::get(), called in /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php on line 31 and defined in [/home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php, line 997]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 138
Cake\ORM\Table::get() - CORE/src/ORM/Table.php, line 997
App\Controller\CuentasController::index() - APP/Controller/CuentasController.php, line 31
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 406
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37



2015-01-16 21:12:25 Error: [Cake\Datasource\Exception\InvalidPrimaryKeyException] Record not found in table "cuentas" with primary key [NULL]
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php(31): Cake\ORM\Table->get()
#1 [internal function]: App\Controller\CuentasController->index()
#2 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Controller/Controller.php(406): call_user_func_array(Array, Array)
#3 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#5 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2015-01-16 21:12:33 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "cuentas"
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php(1036): Cake\ORM\Query->firstOrFail()
#1 /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php(31): Cake\ORM\Table->get(100)
#2 [internal function]: App\Controller\CuentasController->index()
#3 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Controller/Controller.php(406): call_user_func_array(Array, Array)
#4 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#5 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#6 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 {main}


2015-01-16 21:12:41 Warning: Warning (2): Missing argument 1 for Cake\ORM\Table::get(), called in /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php on line 31 and defined in [/home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php, line 997]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 138
Cake\ORM\Table::get() - CORE/src/ORM/Table.php, line 997
App\Controller\CuentasController::index() - APP/Controller/CuentasController.php, line 31
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 406
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37



2015-01-16 21:12:41 Error: [Cake\Datasource\Exception\InvalidPrimaryKeyException] Record not found in table "cuentas" with primary key [NULL]
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php(31): Cake\ORM\Table->get()
#1 [internal function]: App\Controller\CuentasController->index()
#2 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Controller/Controller.php(406): call_user_func_array(Array, Array)
#3 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#5 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2015-01-16 21:12:42 Warning: Warning (2): Missing argument 1 for Cake\ORM\Table::get(), called in /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php on line 31 and defined in [/home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php, line 997]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 138
Cake\ORM\Table::get() - CORE/src/ORM/Table.php, line 997
App\Controller\CuentasController::index() - APP/Controller/CuentasController.php, line 31
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 406
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37



2015-01-16 21:12:43 Error: [Cake\Datasource\Exception\InvalidPrimaryKeyException] Record not found in table "cuentas" with primary key [NULL]
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php(31): Cake\ORM\Table->get()
#1 [internal function]: App\Controller\CuentasController->index()
#2 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Controller/Controller.php(406): call_user_func_array(Array, Array)
#3 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#5 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2015-01-16 21:12:46 Warning: Warning (2): Missing argument 1 for Cake\ORM\Table::get(), called in /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php on line 31 and defined in [/home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/ORM/Table.php, line 997]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 138
Cake\ORM\Table::get() - CORE/src/ORM/Table.php, line 997
App\Controller\CuentasController::index() - APP/Controller/CuentasController.php, line 31
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 406
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37



2015-01-16 21:12:47 Error: [Cake\Datasource\Exception\InvalidPrimaryKeyException] Record not found in table "cuentas" with primary key [NULL]
Request URL: /cakephp/cuentas
Stack Trace:
#0 /home/cra12733/public_html/cakephp/src/Controller/CuentasController.php(31): Cake\ORM\Table->get()
#1 [internal function]: App\Controller\CuentasController->index()
#2 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Controller/Controller.php(406): call_user_func_array(Array, Array)
#3 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 /home/cra12733/public_html/cakephp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CuentasController))
#5 /home/cra12733/public_html/cakephp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


